# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      serviceAccountName: job-server-sa
      containers:
        - name: server
          image: arunant/job-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30080
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-server-sa
  namespace: default
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-server-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-server-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-server-sa
    namespace: default
roleRef:
  kind: Role
  name: job-server-role
  apiGroup: rbac.authorization.k8s.io
---
# Registry Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
# Registry Service
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31804
---
#Cache Images
apiVersion: v1
kind: ConfigMap
metadata:
  name: autograder-dockerfile
data:
  Dockerfile: |
    FROM gradescope/autograder-base:ubuntu-22.04
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkit-dockerfile
data:
  Dockerfile: |
    FROM moby/buildkit:latest
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-images
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gradescope
          image: gcr.io/kaniko-project/executor:latest
          args:
            [
              "--dockerfile=/workspace/Dockerfile",
              "--context=/workspace",
              "--destination=registry:5000/autograder-base:ubuntu-22.04",
              "--insecure",              # allow http push
              "--skip-tls-verify",       # skip TLS check
            ]
          volumeMounts:
            - name: gradescope-dockerfile
              mountPath: /workspace
        - name: buildkit
          image: gcr.io/kaniko-project/executor:latest
          args:
            [
              "--dockerfile=/workspace/Dockerfile",
              "--context=/workspace",
              "--destination=registry:5000/buildkit:latest",
              "--insecure",              # allow http push
              "--skip-tls-verify",       # skip TLS check
            ]
          volumeMounts:
            - name: buildkit-dockerfile
              mountPath: /workspace
      volumes:
        - name: buildkit-dockerfile
          configMap:
            name: buildkit-dockerfile
        - name: gradescope-dockerfile
          configMap:
            name: autograder-dockerfile
